### ISSUE TITLE
Version Control

### ISSUE THREAD

**Issue by gilesknap** [garethnisbet/T-BOTS#4]
I will have a go at taking a fork and tidy it into branches for you.

**Comment by gilesknap** [comment]
I was going to assign this to me, but don't have permission. @garethnisbet maybe you could add me to the project? Thanks.

**Comment by garethnisbet** [comment]
I have restructured the project as suggested. I now suggest you:-
Make a new local clone of this project into a new folder, copy in your latest code, make a commit. Carry on working in the new clone from then on. i.e.

- mkdir github2
- cd github2
- git clone git@github.com:garethnisbet/T-BOTS.git
- cd T-BOTS/TBot/
- cp <~/previous_working folder/*> .
- git commit -am 'adding latest work to new folder structure'
- git push

All good. you can use these to rename and move files as required:-

- git mv
- git rm

**Comment by gilesknap** [comment]
Gareth, I accidentally updated this ticket while logged in as you so you would not have got notifications. See above for steps to use restructured project.
