### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [garethnisbet/T-BOTS#5]
With the file "T-BOTS/TBot/I2C.ino", you have included an issue. The timeout with micros() is useless code. See: https://github.com/TKJElectronics/KalmanFilter/issues/9

**Comment by garethnisbet** [comment]
Thanks Koepel. I've made the change. I haven't properly understood the I2C code so any advice is very welcome.
Gareth

**Comment by Koepel** [comment]
The change is good. Check if the right number of bytes was received, and read them in a for-loop is the best way to do it.

In the `i2cRead()` function does not use a repeated start at the moment. 
It is becoming a common practice to use a repeated start between setting the register-address and reading data. It keeps those two I2C transactions nicely together, but most sensors don't care.
The [`Wire.endTransmission()`](https://www.arduino.cc/en/Reference/WireEndTransmission) in `i2cRead()` has `true` as parameter, but that is the default for a I2C stop. It should be `false` for a Repeated Start.
With a `false`, the `Wire.endTransmission()` omits the I2C Stop, and the I2C Start by the `Wire.requestFrom()` will become the repeated start.

**Comment by garethnisbet** [comment]
Thanks Koepel, I've set the i2cRead() parameter back to false.
